-- Top Places: takes out the demo of seed_demo.sql. The reviewers go with
-- their reviews, and the places with theirs. Made by
-- supabase/tools/generate_seed_demo.js.

begin;

delete from auth.users where email like '%@demo.ro';

delete from public.places where id in (
  'trattoria-nonna-lucia',
  'sushi-kaze',
  'ramen-koen',
  'cafeneaua-artistilor',
  'la-mici-si-bere',
  'taverna-olimpia',
  'green-spoon',
  'brunch-co',
  'the-cellar-wine-bar',
  'roastery-somes',
  'casa-cu-gradina',
  'forno-vecchio',
  'taco-loco',
  'ceainaria-sub-tei',
  'burger-factory',
  'bistro-botanic',
  'bastion-craft-beer',
  'pho-saigon',
  'la-ceaun-banatean',
  'gelateria-bega',
  'steakhouse-unirii',
  'cafe-mercy',
  'bistro-copou',
  'masala-house',
  'brutaria-moldovei',
  'vinoteca-junimea',
  'smoothie-point',
  'pizzeria-palas',
  'bistroul-din-piata-sfatului',
  'pilsner-haus',
  'cafeneaua-de-sub-tampa',
  'pizzeria-schei',
  'ciorbe-si-placinte',
  'kaffeehaus-hermann',
  'crama-sibiana',
  'sushi-nomi',
  'brunch-corner',
  'vinul-turnului',
  'pescaria-farului',
  'taverna-mykonos',
  'sunset-beach-bar',
  'cafe-cazino',
  'burger-port',
  'bistro-art-nouveau',
  'cedrus',
  'patiseria-crisana',
  'casa-baniei-bistro',
  'napoli-express',
  'cafeneaua-englezeasca',
  'faleza-fish-house',
  'vegan-garden',
  'ceainaria-prahova',
  'grill-station',
  'cafeneaua-teatrului',
  'trattoria-mamma-mia',
  'bistro-trandafirilor',
  'udon-bar',
  'hanul-domnesc',
  'cetatea-coffee',
  'old-mine-pub',
  'dunarea-bistro',
  'burger-beer',
  'delta-fish',
  'kyoto-sushi'
);

commit;
